version: '3'
services:
  vproapp:
    image: kumarltd/vproappfix:19
    ports:
      - "8090:8080"

  vprodb:
    image: vevadevops/vprdbfix
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

volumes:
  vprodbdata: {}
