apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: Immediate
reclaimPolicy: Retain
parameters:
  type: gp2
  fsType: ext4
  availabilityZone: us-east-1a  # or -1b, or -1c
