### Vprofile app Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
      - name: vproapp
        image: vevadevops/vproappfix
        ports:
        - name: vproapp-port
          containerPort: 8080
---
# Vprofile app service
apiVersion: v1
kind: Service
metadata:
  name: vproapp
spec:
  ports:
  - port: 80
    targetPort: vproapp-port
    protocol: TCP
  selector:
    app: vproapp
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi

---
# Vprofile DB deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  serviceName: db-service
  replicas: 1
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      volumes:
      - name: mysqldbvolume
        persistentVolumeClaim:
          claimName: ebs-claim
      containers:
      - name: vprodb
        image: vevadevops/vprodbfix
        ports:
        - name: vprodb-port
          containerPort: 3306
        env:
         - name: MYSQL_ROOT_PASSWORD
           value: "vprodbpass"
        volumeMounts:
        - name: mysqldbvolume
          mountPath: "/var/lib/mysql"
---
# Vprofile db deployment Service
apiVersion: v1
kind: Service
metadata:
  name: vprodb
spec:
  ports:
  - port: 3306
    targetPort: vprodb-port
    protocol: TCP
  clusterIP: None
  selector:
    app: vprodb
  type: ClusterIP
